### ISSUE TITLE
Error: retrieving gpg key timed out

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-artifact-tests#100]
It seems a network problem.
Problem job:  [link](http://jenkins.cloudius-systems.com:8080/job/scylla-2.1-ubuntu-deb-16.04-test/label=huginn/175/artifact/latest/job.log)
Another Good job: [link](http://jenkins.cloudius-systems.com:8080/job/scylla-2.1-ubuntu-deb-16.04-test/label=huginn/176/artifact/latest/job.log)

```
2018-06-18 18:09:27,348 process          L0333 INFO | Running 'sudo apt-get install software-properties-common -y'
2018-06-18 18:09:28,850 process          L0420 DEBUG| [stdout] Reading package lists...
2018-06-18 18:09:29,127 process          L0420 DEBUG| [stdout] Building dependency tree...
2018-06-18 18:09:29,127 process          L0420 DEBUG| [stdout] Reading state information...
2018-06-18 18:09:29,301 process          L0420 DEBUG| [stdout] software-properties-common is already the newest version (0.96.20.7).
2018-06-18 18:09:29,301 process          L0420 DEBUG| [stdout] 0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
2018-06-18 18:09:29,303 process          L0333 INFO | Running 'sudo add-apt-repository -y ppa:scylladb/ppa'
2018-06-18 18:09:30,454 process          L0420 DEBUG| [stderr] gpg: keyring `/tmp/tmpy2ida4l7/secring.gpg' created
2018-06-18 18:09:30,454 process          L0420 DEBUG| [stderr] gpg: keyring `/tmp/tmpy2ida4l7/pubring.gpg' created
2018-06-18 18:09:30,455 process          L0420 DEBUG| [stderr] gpg: requesting key 60EF3F5B from hkp server keyserver.ubuntu.com
2018-06-18 18:10:00,573 process          L0420 DEBUG| [stdout] Error: retrieving gpg key timed out.
2018-06-18 18:10:05,029 process          L0420 DEBUG| [stdout] gpgkeys: key D65F6121227931DAD907B91F6B2BFD3660EF3F5B can't be retrieved
2018-06-18 18:10:05,030 process          L0420 DEBUG| [stderr] gpg: no valid OpenPGP data found.
2018-06-18 18:10:05,030 process          L0420 DEBUG| [stderr] gpg: Total number processed: 0
2018-06-18 18:10:05,030 process          L0420 DEBUG| [stderr] gpg: keyserver communications error: keyserver helper general error
2018-06-18 18:10:05,030 process          L0420 DEBUG| [stderr] gpg: keyserver communications error: unknown pubkey algorithm
2018-06-18 18:10:05,030 process          L0420 DEBUG| [stderr] gpg: keyserver receive failed: unknown pubkey algorithm
2018-06-18 18:10:05,048 stacktrace       L0036 ERROR| 
2018-06-18 18:10:05,048 stacktrace       L0039 ERROR| Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado-36.3-py2.7.egg/avocado/core/test.py:436
2018-06-18 18:10:05,049 stacktrace       L0042 ERROR| Traceback (most recent call last):
2018-06-18 18:10:05,049 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-2.1-ubuntu-deb-16.04-test/label/huginn/scylla-artifacts.py", line 707, in setUp
2018-06-18 18:10:05,050 stacktrace       L0042 ERROR|     self.scylla_setup()
2018-06-18 18:10:05,050 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-2.1-ubuntu-deb-16.04-test/label/huginn/scylla-artifacts.py", line 693, in scylla_setup
2018-06-18 18:10:05,050 stacktrace       L0042 ERROR|     installer.run()
2018-06-18 18:10:05,050 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-2.1-ubuntu-deb-16.04-test/label/huginn/scylla-artifacts.py", line 303, in run
2018-06-18 18:10:05,050 stacktrace       L0042 ERROR|     pkgs = self.env_setup()
2018-06-18 18:10:05,050 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-2.1-ubuntu-deb-16.04-test/label/huginn/scylla-artifacts.py", line 446, in env_setup
2018-06-18 18:10:05,050 stacktrace       L0042 ERROR|     self.prepare_extend_repo()
2018-06-18 18:10:05,050 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-2.1-ubuntu-deb-16.04-test/label/huginn/scylla-artifacts.py", line 440, in prepare_extend_repo
2018-06-18 18:10:05,050 stacktrace       L0042 ERROR|     process.run('sudo add-apt-repository -y ppa:scylladb/ppa', shell=True)
2018-06-18 18:10:05,050 stacktrace       L0042 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado-36.3-py2.7.egg/avocado/utils/process.py", line 1031, in run
2018-06-18 18:10:05,050 stacktrace       L0042 ERROR|     raise CmdError(cmd, sp.result)
2018-06-18 18:10:05,050 stacktrace       L0042 ERROR| CmdError: Command 'sudo add-apt-repository -y ppa:scylladb/ppa' failed (rc=1)
2018-06-18 18:10:05,050 stacktrace       L0043 ERROR| 
```

**Comment by amoskong** [comment]
The success log in job 176 ([link](http://jenkins.cloudius-systems.com:8080/job/scylla-2.1-ubuntu-deb-16.04-test/label=huginn/176/artifact/latest/job.log))

```
2018-06-19 13:20:12,636 process          L0333 INFO | Running 'sudo apt-get install software-properties-common -y'
2018-06-19 13:20:14,134 process          L0420 DEBUG| [stdout] Reading package lists...
2018-06-19 13:20:14,409 process          L0420 DEBUG| [stdout] Building dependency tree...
2018-06-19 13:20:14,410 process          L0420 DEBUG| [stdout] Reading state information...
2018-06-19 13:20:14,582 process          L0420 DEBUG| [stdout] software-properties-common is already the newest version (0.96.20.7).
2018-06-19 13:20:14,582 process          L0420 DEBUG| [stdout] 0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
2018-06-19 13:20:14,584 process          L0333 INFO | Running 'sudo add-apt-repository -y ppa:scylladb/ppa'
2018-06-19 13:20:15,857 process          L0420 DEBUG| [stderr] gpg: keyring `/tmp/tmpbf522t1h/secring.gpg' created
2018-06-19 13:20:15,858 process          L0420 DEBUG| [stderr] gpg: keyring `/tmp/tmpbf522t1h/pubring.gpg' created
2018-06-19 13:20:15,858 process          L0420 DEBUG| [stderr] gpg: requesting key 60EF3F5B from hkp server keyserver.ubuntu.com
2018-06-19 13:20:16,111 process          L0420 DEBUG| [stderr] gpg: /tmp/tmpbf522t1h/trustdb.gpg: trustdb created
2018-06-19 13:20:16,111 process          L0420 DEBUG| [stderr] gpg: key 60EF3F5B: public key "Launchpad PPA for ScyllaDB" imported
2018-06-19 13:20:16,111 process          L0420 DEBUG| [stderr] gpg: Total number processed: 1
2018-06-19 13:20:16,111 process          L0420 DEBUG| [stderr] gpg:               imported: 1  (RSA: 1)
2018-06-19 13:20:16,143 process          L0420 DEBUG| [stdout] OK
2018-06-19 13:20:16,160 process          L0333 INFO | Running 'sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B2BFD3660EF3F5B'
2018-06-19 13:20:16,204 process          L0420 DEBUG| [stdout] Executing: /tmp/tmp.Q2wiNKKOaL/gpg.1.sh --keyserver
2018-06-19 13:20:16,204 process          L0420 DEBUG| [stdout] keyserver.ubuntu.com
2018-06-19 13:20:16,204 process          L0420 DEBUG| [stdout] --recv-keys
2018-06-19 13:20:16,204 process          L0420 DEBUG| [stdout] 6B2BFD3660EF3F5B
2018-06-19 13:20:16,206 process          L0420 DEBUG| [stderr] gpg: requesting key 60EF3F5B from hkp server keyserver.ubuntu.com
2018-06-19 13:20:16,478 process          L0420 DEBUG| [stderr] gpg: key 60EF3F5B: "Launchpad PPA for ScyllaDB" not changed
2018-06-19 13:20:16,478 process          L0420 DEBUG| [stderr] gpg: Total number processed: 1
2018-06-19 13:20:16,478 process          L0420 DEBUG| [stderr] gpg:              unchanged: 1
2018-06-19 13:20:16,536 process          L0333 INFO | Running 'sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 17723034C56D4B19'
2018-06-19 13:20:16,580 process          L0420 DEBUG| [stdout] Executing: /tmp/tmp.E9rnOcRq9O/gpg.1.sh --keyserver
2018-06-19 13:20:16,581 process          L0420 DEBUG| [stdout] keyserver.ubuntu.com
2018-06-19 13:20:16,581 process          L0420 DEBUG| [stdout] --recv-keys
2018-06-19 13:20:16,581 process          L0420 DEBUG| [stdout] 17723034C56D4B19
2018-06-19 13:20:16,582 process          L0420 DEBUG| [stderr] gpg: requesting key C56D4B19 from hkp server keyserver.ubuntu.com
2018-06-19 13:20:16,841 process          L0420 DEBUG| [stderr] gpg: key C56D4B19: public key "ScyllaDB Package Signing Key 2018 <security@scylladb.com>" imported
2018-06-19 13:20:16,842 process          L0420 DEBUG| [stderr] gpg: Total number processed: 1
2018-06-19 13:20:16,842 process          L0420 DEBUG| [stderr] gpg:               imported: 1  (RSA: 1)
```
