### ISSUE TITLE
scylla_setup: Timeout in process.run() doesn't work with 'sudo'

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-artifact-tests#103]
It should be a framework.

```
# cat test.py
from avocado.utils import process

process.run('sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/sdb --no-cpuscaling-setup --no-raid-setup --no-coredump-setup', shell=True, verbose=True, timeout=10)
```

**Comment by amoskong** [comment]
I found the timeout doesn't work if cmd executes with `sudo`
```
# Timeout works well:
process.run('sleep 10', shell=True, verbose=True, timeout=1)


# Timeout doesn't work, it will stuck.
process.run('sudo sleep 10', shell=True, verbose=True, timeout=1)
```

**Comment by amoskong** [comment]
Actually it's not a bug, we can solve the problem by executing avocado with `sudo`.

The main process doesn't has permission to kill subprocess (starts by sudo)
```
$ python
Python 2.7.10 (default, Oct  6 2017, 22:29:07) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from avocado.utils import process
>>> process.run('sudo sleep 10', timeout=1)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 1082, in run
    self.function(*self.args, **self.kwargs)
  File "avocado/utils/process.py", line 507, in send_signal
    self._popen.send_signal(sig)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1554, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 1] Operation not permitted

Command: sudo sleep 10
Exit status: 0
Duration: 10.0446128845
Stdout:

Stderr:
```

```
$ sudo python
Python 2.7.10 (default, Oct  6 2017, 22:29:07) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from avocado.utils import process
>>> process.run('sudo sleep 10', timeout=1)
Command: sudo sleep 10
Exit status: 0
Duration: 1.0067679882
Stdout:

Stderr:


>>> 
```

**Comment by amoskong** [comment]
* Test with root user:
Timeout doesn't work when sudo is used even for root user.

```
[root@localhost muninn]# python
Python 2.7.5 (default, Apr 11 2018, 07:36:10) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from avocado.utils import process
>>> process.run('sudo sleep 10', timeout=1)
Command: sudo sleep 10
Exit status: 0
Duration: 10.0067999363
Stdout:

Stderr:


>>> process.run('sleep 10', timeout=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/avocado/utils/process.py", line 1031, in run
    raise CmdError(cmd, sp.result)
avocado.utils.process.CmdError: Command 'sleep 10' failed (rc=-15)
```
