### ISSUE TITLE
docker failed to delete container

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-artifact-tests#140]
https://jenkins.scylladb.com/view/scylla-3.3/job/scylla-3.3/job/build-docker/11/console

```
10:27:00  avocado.test: Running 'docker rmi df46504e1cfd c9477cd895a2'
10:27:00  avocado.test: [stderr] Error response from daemon: conflict: unable to delete df46504e1cfd (must be forced) - image is being used by stopped container 560b9eac94f7
10:27:00  avocado.test: [stderr] Error response from daemon: conflict: unable to delete c9477cd895a2 (must be forced) - image is being used by stopped container 24065c68204f
10:27:00  avocado.test: 
10:27:00  avocado.test: Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:436
10:27:00  avocado.test: Traceback (most recent call last):
10:27:00  avocado.test:   File "/jenkins/workspace/scylla-3.3/build-docker/scylla-artifact-tests/scylla_docker.py", line 220, in setUp
10:27:00  avocado.test:     self.docker.update_image()
10:27:00  avocado.test:   File "/jenkins/workspace/scylla-3.3/build-docker/scylla-artifact-tests/scylla_docker.py", line 55, in update_image
10:27:00  avocado.test:     self.clean_old_images()
10:27:00  avocado.test:   File "/jenkins/workspace/scylla-3.3/build-docker/scylla-artifact-tests/scylla_docker.py", line 50, in clean_old_images
10:27:00  avocado.test:     self._cmd('rmi {}'.format(images_str), timeout=90)
10:27:00  avocado.test:   File "/jenkins/workspace/scylla-3.3/build-docker/scylla-artifact-tests/scylla_docker.py", line 43, in _cmd
10:27:00  avocado.test:     raise DockerCommandError('command: {}, error: {}, output: {}'.format(cmd, res.stderr, res.stdout))
10:27:00  avocado.test: DockerCommandError: command: rmi df46504e1cfd c9477cd895a2, error: Error response from daemon: conflict: unable to delete df46504e1cfd (must be forced) - image is being used by stopped container 560b9eac94f7
10:27:00  avocado.test: Error response from daemon: conflict: unable to delete c9477cd895a2 (must be forced) - image is being used by stopped container 24065c68204f
10:27:00  avocado.test: , output: 
10:27:00  avocado.test: 
10:27:00  avocado.test: ERROR 1-scylla_docker.py:ScyllaDockerSanity.test_basic_stress -> TestSetupFail: command: rmi df46504e1cfd c9477cd895a2, error: Error response from daemon: conflict: unable to delete df46504e1cfd (must be forced) - image is being used by stopped container 560b9eac94f7
10:27:00  Error response from daemon: conflict: unable to delete c9477cd895a2 (must be forced) - image is being used by stopped container 24065c68204f
10:27:00  , output: 
10:27:00  avocado.test: 
10:27:00  
10:27:00  Error receiving message from test: <type 'exceptions.ImportError'> -> No module named scylla_docker
10:27:00  
10:27:00  Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/runner.py:75
10:27:00  Traceback (most recent call last):
10:27:00    File "/usr/lib64/python2.7/multiprocessing/queues.py", line 376, in get
10:27:00      return recv()
10:27:00  ImportError: No module named scylla_docker
10:27:00  
10:27:00  avocado.test: ERROR 1-scylla_docker.py:ScyllaDockerSanity.test_basic_stress -> TestAbortedError: Test aborted unexpectedly
10:27:00  ERROR (2.15 s)
10:27:00  avocado.sysinfo: Commands configured by file: /etc/avocado/sysinfo/commands
10:27:00  avocado.sysinfo: Files configured by file: /etc/avocado/sysinfo/files
10:27:00  avocado.sysinfo: Profilers configured by file: /etc/avocado/sysinfo/profilers
10:27:00  avocado.sysinfo: Profilers declared: ['vmstat 1', 'journalctl -f']
10:27:00  avocado.sysinfo: Profiler disabled
10:27:00  avocado.test: PARAMS (key=timeout, path=*, default=None) => None
10:27:00  avocado.test: START 2-scylla_docker.py:ScyllaDockerSanity.test_stress_with_restart
10:27:00  avocado.test: PARAMS (key=docker_image, path=*, default=scylladb/scylla-nightly) => 'scylladb/scylla:3.3.rc0-202002051019'
10:27:00  avocado.test: PARAMS (key=start_timeout, path=*, default=30) => 60
10:27:00   (2/2) scylla_docker.py:ScyllaDockerSanity.test_stress_with_restart:  scylla_docker: update scylla image
10:27:00  avocado.test: Running 'docker pull scylladb/scylla:3.3.rc0-202002051019'
10:27:02  avocado.test: [stdout] 3.3.rc0-202002051019: Pulling from scylladb/scylla
10:27:02  avocado.test: [stdout] Digest: sha256:2bbe5ff5a5ee1d17d27ab5fe823f8e0519fe8f620b82924dc6d88ba2bd671a0c
10:27:02  avocado.test: [stdout] Status: Image is up to date for scylladb/scylla:3.3.rc0-202002051019
10:27:02  avocado.test: Running 'docker images -f "dangling=true" -q'
10:27:02  avocado.test: [stdout] df46504e1cfd
10:27:02  avocado.test: [stdout] c9477cd895a2
10:27:02  avocado.test: Running 'docker rmi df46504e1cfd c9477cd895a2'
10:27:02  avocado.test: [stderr] Error response from daemon: conflict: unable to delete df46504e1cfd (must be forced) - image is being used by stopped container 560b9eac94f7
10:27:02  avocado.test: [stderr] Error response from daemon: conflict: unable to delete c9477cd895a2 (must be forced) - image is being used by stopped container 24065c68204f
10:27:02  avocado.test: 
10:27:02  avocado.test: Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:436
10:27:02  avocado.test: Traceback (most recent call last):
10:27:02  avocado.test:   File "/jenkins/workspace/scylla-3.3/build-docker/scylla-artifact-tests/scylla_docker.py", line 220, in setUp
10:27:02  avocado.test:     self.docker.update_image()
10:27:02  avocado.test:   File "/jenkins/workspace/scylla-3.3/build-docker/scylla-artifact-tests/scylla_docker.py", line 55, in update_image
10:27:02  avocado.test:     self.clean_old_images()
10:27:02  avocado.test:   File "/jenkins/workspace/scylla-3.3/build-docker/scylla-artifact-tests/scylla_docker.py", line 50, in clean_old_images
10:27:02  avocado.test:     self._cmd('rmi {}'.format(images_str), timeout=90)
10:27:02  avocado.test:   File "/jenkins/workspace/scylla-3.3/build-docker/scylla-artifact-tests/scylla_docker.py", line 43, in _cmd
10:27:02  avocado.test:     raise DockerCommandError('command: {}, error: {}, output: {}'.format(cmd, res.stderr, res.stdout))
10:27:02  avocado.test: DockerCommandError: command: rmi df46504e1cfd c9477cd895a2, error: Error response from daemon: conflict: unable to delete df46504e1cfd (must be forced) - image is being used by stopped container 560b9eac94f7
10:27:02  avocado.test: Error response from daemon: conflict: unable to delete c9477cd895a2 (must be forced) - image is being used by stopped container 24065c68204f
10:27:02  avocado.test: , output: 
10:27:02  avocado.test: 
10:27:02  avocado.test: ERROR 2-scylla_docker.py:ScyllaDockerSanity.test_stress_with_restart -> TestSetupFail: command: rmi df46504e1cfd c9477cd895a2, error: Error response from daemon: conflict: unable to delete df46504e1cfd (must be forced) - image is being used by stopped container 560b9eac94f7
10:27:02  Error response from daemon: conflict: unable to delete c9477cd895a2 (must be forced) - image is being used by stopped container 24065c68204f
10:27:02  , output: 
10:27:02  avocado.test: 
10:27:02  
10:27:02  Error receiving message from test: <type 'exceptions.ImportError'> -> No module named scylla_docker
10:27:02  
10:27:02  Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/runner.py:75
10:27:02  Traceback (most recent call last):
10:27:02    File "/usr/lib64/python2.7/multiprocessing/queues.py", line 376, in get
10:27:02      return recv()
10:27:02  ImportError: No module named scylla_docker
10:27:02  
10:27:02  avocado.test: ERROR 2-scylla_docker.py:ScyllaDockerSanity.test_stress_with_restart -> TestAbortedError: Test aborted unexpectedly
10:27:02  ERROR (2.03 s)
10:27:02  avocado.sysinfo: Not logging /proc/slabinfo (lack of permissions)
10:27:02  RESULTS    : PASS 0 | ERROR 2 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
10:27:02  JOB HTML   : /jenkins/workspace/scylla-3.3/build-docker/job-2020-02-05T10.26-f38073d/html/results.html
10:27:02  TESTS TIME : 4.18 s
10:27:02  avocado.test: Test results available in /jenkins/workspace/scylla-3.3/build-docker/job-2020-02-05T10.26-f38073d
```

**Comment by fruch** [comment]
@amoskong it don't think it smart that test are trying to delete images, since seems some of the layer are in use.
we should leave that to the releng team to run jobs to clear old unused images/containers from all workers

**Comment by yaronkaikov** [comment]
@amoskong @roydahan @fruch again docker test failed - https://jenkins.scylladb.com/view/master/job/scylla-master/job/build-docker/164/

**Comment by amoskong** [comment]
I will fix as @fruch suggested.

**Comment by yaronkaikov** [comment]
@amoskong Thanks. for now i cleared the images manually and triggered the job again

**Comment by amoskong** [comment]
The situation doesn't happen very frequently, so process manually in the
past.
