### ISSUE TITLE
scylla-master-centos-rpm-test failed: node_exporter already installed

### ISSUE THREAD

**Issue by abvgedeika** [scylladb/scylla-artifact-tests#50]
http://jenkins.cloudius-systems.com/job/scylla-master-centos-rpm-test/label=muninn/154/artifact/latest/job.log

```
2017-04-20 17:16:03,577 process          L0420 DEBUG| [stdout] Do you want to install node exporter and export Prometheus data from the node?
2017-04-20 17:16:03,577 process          L0420 DEBUG| [stdout] Answer yes to install it; answer no to skip this installation.
2017-04-20 17:16:03,579 process          L0420 DEBUG| [stdout] node_exporter already installed
2017-04-20 17:16:03,580 process          L0420 DEBUG| [stdout] [0;31mnode exporter setup failed. press any key to continue...[0m
2017-04-20 17:16:03,581 stacktrace       L0036 ERROR| 
2017-04-20 17:16:03,581 stacktrace       L0039 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:436
2017-04-20 17:16:03,581 stacktrace       L0042 ERROR| Traceback (most recent call last):
2017-04-20 17:16:03,581 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master-centos-rpm-test/label/muninn/scylla-artifacts.py", line 624, in setUp
2017-04-20 17:16:03,581 stacktrace       L0042 ERROR|     self.scylla_setup()
2017-04-20 17:16:03,581 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master-centos-rpm-test/label/muninn/scylla-artifacts.py", line 619, in scylla_setup
2017-04-20 17:16:03,581 stacktrace       L0042 ERROR|     installer.run()
2017-04-20 17:16:03,581 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-master-centos-rpm-test/label/muninn/scylla-artifacts.py", line 278, in run
2017-04-20 17:16:03,581 stacktrace       L0042 ERROR|     process.run('yes "" | sudo /usr/lib/scylla/scylla_setup', shell=True)
2017-04-20 17:16:03,581 stacktrace       L0042 ERROR|   File "/usr/lib/python2.7/site-packages/avocado/utils/process.py", line 1031, in run
2017-04-20 17:16:03,581 stacktrace       L0042 ERROR|     raise CmdError(cmd, sp.result)
2017-04-20 17:16:03,581 stacktrace       L0042 ERROR| CmdError: Command 'yes "" | sudo /usr/lib/scylla/scylla_setup' failed (rc=1)
2017-04-20 17:16:03,582 stacktrace       L0043 ERROR| 
2017-04-20 17:16:03,582 test             L0581 ERROR| ERROR 2-/root/avocado/tests/jenkins/slave/workspace/scylla-master-centos-rpm-test/label/muninn/scylla-artifacts.py:ScyllaArtifactSanity.test_after_stop_start -> TestSetupFail: Command 'yes "" | sudo /usr/lib/scylla/scylla_setup' failed (rc=1)
2017-04-20 17:16:03,582 test             L0568 INFO | 
```
possible solution could be like 
```
sudo /usr/lib/scylla/scylla_setup <<-END
Y
Y
Y
Y
Y
N
Y
Y
Y
Y
N
END
```

seems like due to https://github.com/scylladb/scylla-artifact-tests/commit/074a906d726826b3b2c99acaa2a113111722d08e

**Comment by abvgedeika** [comment]
assigned to @amoskong

**Comment by abvgedeika** [comment]
fixed via https://github.com/scylladb/scylla-artifact-tests/pull/49

**Comment by amoskong** [comment]
@abvgedeika It's not good to use fixed answer series, the interaction might change.

`sudo /usr/lib/scylla/scylla_setup --no-cpuscaling-setup --no-raid-setup --nic eth0`

**Comment by amoskong** [comment]
The problem already fixed.
